name: emoji_feedback
description: An mood feedback component which could be used for rating the user's mood.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:
    - assets/
